name: Build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Need to download all history in order
          # to make the tests work properly
          fetch-depth: 0
      - uses: docker://ffurrer/bats:latest
        with:
          args: "--recursive ."
      - uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.0.7
          branches: |
            [
              'v2'
            ]
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/git@9.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
